#!/usr/bin/env bash
#
# Author: 	Britta Bouwman
# Date:		2018-July-16
# Title:	BED_max100_binned.sh
# Aim:		Take BED files generated by the BLISS mapping pipeline, and do the following:
# 				1. Add 'chr', remove chromosomes MT and GL.  
# 				2. Create one line for each UMI-DSB reported, with a max of 100 per location.
# 				3. Generate BED file with 2 additional columns (0 and +)
# 				4. Bedtools Intersect: DSB count per 1kb bin. 
#						! You need a prebinned genome [bedtools makewindows]
# 				5. Remove all windows without breaks (zeroes).
# 				6. Perform statistics with 'sta', find 90th percentile.
# 				7. Filter for those windows that belong to the 90th percentile (top 10%.  


# To run: bash bed_cleaning_binning_90thpercentile.sh experimentname  
###################################################################################################

# Define variables
experiment=$1									# Library name (BB100 or BB100-K562) 
hg1kb=$HOME/Tools/Genomes/hg19_w1000_sorted.bed # File with binned human genome

# Prepare directory structure
beddir=$HOME/Data/BLISS/BEDs/Original 
bin=$HOME/Tools/Scripts
datadir=$HOME/Data/BLISS/BEDs/Output && mkdir -p $datadir/$experiment 
indata=$datadir/$experiment/indata/ && mkdir -p $indata
outdata=$datadir/$experiment/outdata/ && mkdir -p $outdata


# Load bed file. Important: check whether your bedfile already contains 'chr' or not. 
# If so, omit the 'sed' part in the 'cat' pipe below! Otherwise you get 'chrchr'
###################################################################################################
echo "Working on exp.:" $experiment 
bed=$(find $beddir -maxdepth 1 -type f -iname "*$experiment*.bed") #-print
#echo $bed

# Prevent overwriting/extending older files. 
# If desired, manually rename the datadirectory after completing the script before rerunning.
rm -f $indata"/"$experiment"_improved.txt" 
rm -f $indata"/"$experiment"_max100_split.bed"
rm -f $outdata"/"$experiment"_DSBsin1kbbins.txt" 
rm -f $outdata"/"$experiment"_sta_summary.txt"
rm -f $outdata"/"$experiment"_90thpercentile_mostbroken.txt"

# Add chr, remove GL, MT: 
cat $bed | grep -v GL | grep -v MT | sed "s/^/chr/" > $indata"/"$experiment"_improved.txt" 
# To use instead when 'chr' is present already: 
#cat $bed | grep -v GL | grep -v MT > $indata"/"$experiment"_improved.txt" 
echo "Created in indata" $experiment"_improved.txt"

# Add new DSB to new line, add columns, stop when reaching 100:
cat $indata"/"$experiment"_improved.txt" | awk '{sum=0;for(i=1; i<=$4; i++){sum += 1; if (sum > 100) break; else print $1 "\t" $2 "\t" $3 "\t" i "\t0\t+"}}' > $indata"/"$experiment"_max100_split.bed"
echo "Created in indata:" $experiment"_max100_split.bed"

# Run bedtools to intersect binned human genome with the exp_temp2.bed file. Remove bins with 0 overlap counts. 
bedtools intersect -a $hg1kb -b $indata"/"$experiment"_max100_split.bed" -c | awk '{if($5 > 0) print $0}' > $outdata"/"$experiment"_DSBsin1kbbins.txt" 
echo "Created in outdata" $experiment"_DSBsin1kbbins.txt" 

# Statistical of most broken windows; sta outputs total breaks (N), minimal (min), maximum (max), quartiles (q1, median, q3,), total windows with a break (sum), mean, and in this case 90th percentile   
cat $outdata"/"$experiment"_DSBsin1kbbins.txt" | cut -f5 | sta --sum --min --max --mean --median --q --p 90 --transpose > $outdata"/"$experiment"_sta_summary.txt"
echo "Created in outdata:" $experiment"_sta_summary.txt"

# Then find a way to select the 90th percentage cut-off that belongs to the specific dataset
p90=$(cat $outdata"/"$experiment"_sta_summary.txt" | grep '90th' | cut -f2)
echo "90th percentile cutoff for UMI-DSBs per 1kb window will be set at >=" $p90 

# Now use the p90 cut-off to filter the windows and keep only the top 10% most broken windows. 
cat $outdata"/"$experiment"_DSBsin1kbbins.txt" | awk -v threshold=$p90 '{if($5 >= threshold) {print $0}}' > $outdata"/"$experiment"_90thpercentile_mostbroken.txt"
cat $outdata"/"$experiment"_90thpercentile_mostbroken.txt" | awk '{print $1 "\t" $2 "\t" $3 "\t" $5 "\t0\t+"}' > $outdata"/"$experiment"_90thpercentile_mostbroken.bed"
echo "Created in outdata:" $experiment"_90thpercentile_mostbroken.txt and a BED file with the same name"

